{% set name = "bilby" %}
{% set version = "0.5.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b53676d313e1964bcf1db57817fad479ddb8bf9e119d517ae037efbe4230a46d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  entry_points:
    - bilby_plot=cli_bilby.plot_multiple_posteriors:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - corner
    - deepdish
    - dill
    - dynesty
    - future
    - matplotlib >=2.0
    - numpy >=1.9
    - pandas
    - scipy

test:
  commands:
    - setx MPLBACKEND "Agg"  # [win]
    - export MPLBACKEND="Agg"  # [unix]
    - bilby_plot --help
    - python -c "import bilby"
    - python -c "import bilby.core"
    - python -c "import bilby.gw"
    - python -c "import bilby.hyper"
    - python -c "import cli_bilby"

about:
  home: https://git.ligo.org/lscsoft/bilby
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: A user-friendly Bayesian inference library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - GregoryAshton
