{% set name = "bilby" %}
{% set version = "0.5.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d74dab14e531096a62d825f3a44624d9431579ad6e5f753fbea1da2ad870f8a2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - bilby_plot = cli_bilby.plot_multiple_posteriors:main
    - bilby_result = cli_bilby.bilby_result:main
    - bilby_convert_resume = cli_bilby.resume:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - corner
    - deepdish
    - dill
    - dynesty
    - future
    - matplotlib >=2.0
    - numpy >=1.9
    - pandas
    - scipy
    - tqdm

test:
  commands:
    - setx MPLBACKEND "Agg"  # [win]
    - export MPLBACKEND="Agg"  # [unix]
    - bilby_plot --help
    - bilby_result --help
    - bilby_convert_resume --help
    - python -c "import bilby"
    - python -c "import bilby.core"
    - python -c "import bilby.core.sampler"
    - python -c "import bilby.gw"
    - python -c "import bilby.gw.detector"
    - python -c "import bilby.gw.sampler"
    - python -c "import bilby.hyper"
    - python -c "import cli_bilby"

about:
  home: https://git.ligo.org/lscsoft/bilby
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A user-friendly Bayesian inference library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - GregoryAshton
