travis:
  secure:
    BINSTAR_TOKEN: ZE3oOVEZzf7bFnG5Y518cKhv2EFeiRYnRCpTAwt/NnI0nouo3OugPYPy9tDfp6Jyd2rne7K9EsI8RL6Od2X3XWNnrmC98VUGraVMUmbajWe130+lQgBTd23SB2hkMHo6Iqyacy9VnZfk/vZPAtlZEe7kiRY9qqr8G/S/5qvae+EBimOKT0MvGs1PwvaJ9s+m0qiUd7Bny5Qs6G6TmUpaqDihKwF7llaFflqYKreIfUWLEbgmYlDpQ91Jh0GzfDoFGQ0fuBihoXBeZFv5SqXX0CLHn7RS9cKT7hs7GnFAy7SjkFce+nv5oMMXQqOBqRUkJGeg0AmcAscY2ErpcVN0QsI42ehAchgFCA34edXJ0i53ZbMQhwC6dxwhl1orDnjp1D8YlBcz62J8sHmdbS9MscOUUdJ0P0VPnB20Q1Y28NhnmCnYNis8mzJs46xGZ6hLzO8IfR00PsIlL+ICJq/hmTQHhfT6RgwswHA5zkttUYu+BjNunbRWM06neBd9apj3EALPe+x5dYI0FePouxPi9adHOdhqhykU1GFF2ptMD8SZeqgNVwoAX9QBFMyfgsDB9E4c7uoawkmUw9Ey4h6DAct1a6UlJWY2NTghiIkFBok6Evy41nN87U4BmyQ6QgCH8/k14gZ/R3p/TVrXX7rHUuuaEQu3fr2ThW0ud5gCHqw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
